{
  try {
    m_result=value;
    onResponse(value);
  }
 catch (  UmbrellaException exception) {
    Throwable wrappedException=exception.getCauses().iterator().next();
    onFailure(wrappedException);
  }
catch (  RuntimeException error) {
    onFailure(error);
  }
}
